platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5.4'
pod 'SDWebImage', '~> 3.7.3'
#pod 'EaseMobSDKFull',:git => 'https://github.com/easemob/sdk-ios-cocoapods-integration.git'        #环信
pod 'EaseMobSDKFull', '~> 2.1.7'
pod 'MBProgressHUD', '~> 0.9.1'         #HUD
pod 'UICKeyChainStore', '~> 2.0.6'      #存放用户账号密码组件
pod 'Reachability', '~> 3.2'            #判断网络
pod 'RMAppStoreVersionCheck', '~> 1.0.1'#App Store的版本检查
pod 'MJRefresh', '~> 2.4.7'
pod 'FMDB', '~> 2.5'
pod 'MJExtension', '~> 2.3.4'
pod 'DZNEmptyDataSet', '~> 1.5.2'      #tableview无内容时显示
#pod 'GPUImage', '~> 0.1.6'
pod 'FXBlurView', '~> 1.6.3'           #模糊效果
pod 'FDFullscreenPopGesture', '~> 1.1' #全屏滑动手势,只需要添加这个库就可以执行,不需要代码
pod 'AMap2DMap', '~> 2.5.0'
pod 'AMapSearch', '~> 2.5.0'
pod 'HZActionSheet', '~> 1.0.1'        #微信弹出框
pod 'SVWebViewController', '~> 1.0'    #浏览器
#pod 'SVProgressHUD', '~> 1.1.3'       #提示HUD
pod 'UMengAnalytics', '~> 3.5.8'       #友盟统计
pod 'UIImage+ImageWithColor', '~> 1.3' #颜色生成图片
pod 'MWPhotoBrowser', '~> 2.1.1'       #图片浏览

pod 'EaseMobDIYUI', :git => 'https://github.com/AwakenDragon/EaseMobDIYUI.git'

pod 'VoiceConvert',:git => "https://github.com/AwakenDragon/VoiceConvert.git"

pod 'ShareSDK2', '~> 2.12.4'#ShareSDK主模块
pod 'MOBFoundation', '~> 1.3.1'#MOB公共库
pod 'ShareSDK2/Comment'# 评论和赞模块(可选)
pod 'SMSSDK', '~> 2.0.0'#免费短信

